### PR TITLE
fix: onChange event is fired twice when select from search input

### LINKED ISSUE #293: onChange event is fired twice when you change value after using search
To recreate this bug.

`
VirtualSelect.init({
  ...
  search: true,
});

document.querySelector('#sample-select').addEventListener('change', function() {
  console.log(this.value);
});
`

Now when you search a value and select it the change event is fired twice

### PR DESCRIPTION
**Pull request by bes-internal**
when search is enabled, when we enter something to select, the change event is triggered when focus is lost (for example, when clicking on the option itself) and bubble on the main onchange handler of the entire element, which causes unnecessary triggering. 
We just put an explicit handler on the input field to prevent this.

Fixes #293

### CODE REVIEW

File: src/virtual-select.js [hunk 1]
```diff
@@ -448,6 +448,7 @@ export class VirtualSelect {
     this.$toggleAllCheckbox = this.$dropboxContainer.querySelector('.vscomp-toggle-all-checkbox');
 
     this.addEvent(this.$searchInput, 'input', 'onSearch');
+    this.addEvent(this.$searchInput, 'change', 'toPreventEvent');
```
Comment (gnbm) [inline src/virtual-select.js:451]: The method name `toPreventEvent` is ambiguous; consider renaming to `preventChangePropagation` for clarity.

File: src/virtual-select.js [hunk 2]
```diff
@@ -696,6 +697,10 @@ export class VirtualSelect {
     this.setSearchValue(e.target.value, true);
   }
 
+  toPreventEvent(e) {
```
Comment (gnbm) [inline src/virtual-select.js:700]: Add a brief comment explaining its purpose and why it stops propagation of the change event, since, by looking at the code it's not easy to understand.

File: src/virtual-select.js (hunk 1 above)
Comment (gnbm) [inline src/virtual-select.js:451]: Add unit tests to verify that the change event is no longer fired twice when selecting items via the search input.
They should include all scenarios, like when you are in popup mode, inline mode, always opened, setting values programmatically, etc. I would request this since adding this sort of workaround that at first glance seem to be siple can be often dangerous by adding unwanted side effects, so regression testing should be guaranteed

**Review by gnbm — CHANGES_REQUESTED** [review]

File: src/virtual-select.js (hunk 1 above)
Comment (bes-internal) [reply src/virtual-select.js]: I added a basic test over the select from the examples to cover this error. Of course, it would be desirable to add other states, but I'm afraid this is too complicated for me. It would be good if someone added this

File: cypress/e2e/examples.cy.ts [hunk 3]
```diff
@@ -626,3 +626,22 @@ describe('Validation', () => {
...
+  const resid = 'select-onchange-results';
+
+  it('go to section', () => {
+    cy.goToSection('Add Events');
+  });
+
+  it('select 2 in row', () => {
+    cy.open(selid).find('.vscomp-option').first().click();
+    cy.get(`#${resid}`).should('have.text', 'value = 1; count of changes = 1');
+    cy.open(selid).search(123).find('.vscomp-option').first().click();
```
Comment (gnbm) [inline cypress/e2e/examples.cy.ts:643]: Running `npm run validate`, we get the error: 

image

File: docs/examples.md [hunk 4]
```diff
@@ -424,6 +426,22 @@ VirtualSelect.init({
 });
 ```
 
+## Add Events
+
```
[the remark this answers is not in the document]
Comment (bes-internal) [reply docs/examples.md:430]: The tests use the examples section and I will not change it. Perhaps you can then move this example to the events section yourself.

File: docs/assets/script.js [hunk 5]
```diff
@@ -361,4 +361,16 @@ function initPageExamples() {
...
     additionalToggleButtonClasses: 'custom-toggle-button',
   });
+
+  initVirtualSelect({
+    ele: '#select-onchange',
+    search: true,
+    dropboxWrapper: 'self', // needed for onchange unit tests
+  });
+  window.onchangeCount=0;
+  document.querySelector('#select-onchange').addEventListener('change', function() {
```
[the remark this answers is not in the document]
Comment (bes-internal) [reply docs/assets/script.js:371]: Well, show me how to do it. I don't see a more illustrative example than doing it like it is now.

[the remark this answers is not in the document]
Comment (bes-internal) [reply docs/assets/script.js:371]: His example doesn't work. Because he declares the variable in the wrong scope. You need to declare the variable somewhere higher in the code. This loses its appeal in clarity and loses the connection with the example for users.
